name: BuildAndDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install modules
        run: npm ci
      - name: Test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install modules
        run: npm ci
      - name: Test
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install modules
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
